<?php

namespace app\modules\comments\widgets;

use app\modules\comments\models\Comments;
use Yii;

/**
 * @var $module \app\modules\comments\Module
 * @var $show boolean
 * @var $showForm boolean
 * */

class CommentsWidget extends \yii\base\Widget
{
    private $module;
    private $show = false;
    private $currentComments;

    public $entity = null;
    public $entityID = null;

    public function init()
    {
        $this->module = Yii::$app->getModule('comments');
        $this->isShow();

        if (!$this->show) {
            return false;
        }

        $this->currentComments = Comments::find()
                                    ->where(['entity_id' => $this->entityID])
                                    ->andWhere(['LIKE', 'entity', $this->entity])
                                    ->all();

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if (!$this->show) {
            return false;
        }

        print CommentsListWidget::widget([
            'entity'         => $this->entity,
            'entityID'       => $this->entityID,
            'currentComments'  => $this->currentComments,
        ]);

        if (!$this->isShowForm()) {
            return false;
        }

        print CommentFormWidget::widget([
            'entity'         => $this->entity,
            'entityID'       => $this->entityID,
        ]);
    }

    private function isShow()
    {
        if (!empty($this->entity) && !empty($this->entityID)) {
            $this->show = true;
        }
    }

    private function isShowForm()
    {
        return ($this->module->getShowForm() && $this->show) ? true : false;
    }
}